#!/bin/bash
#AUTOR:JOHNNI
#POLO:SJBV
Hora=`date +%H`
 
if [ $Hora -lt "12" ]
then
                echo "Bom dia!"
else       
                if [ $Hora -lt "18" ]
                then
                                echo "Boa tarde!"
                else
                                echo "Boa noite!"
                fi
fi
